#Application
spring.application.name=notification-api
server.port=8081

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/notifyx
spring.datasource.username=notifyx
spring.datasource.password=notifyx123

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always